name: Validate Bicep

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Validate Bicep
      run: |
        az bicep build --file main.bicep
